name: VigilCD CI Checks

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
            - "3.11"
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    defaults:
      run:
        working-directory: ./VigilCD/
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv with cache and setup python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "0.9.13"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff Linter
        run: uv run ruff check . --exit-zero

      - name: Run Ruff Formatter
        run: uv run ruff format . --check

      - name: Minimize uv cache
        run: uv cache prune --ci