name: VigilCD CI Checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - development
      - staging
  pull_request:
  schedule:
    - cron: '00 1 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
            - "3.14"
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    defaults:
      run:
        working-directory: ./VigilCD/
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'merge_group' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/development", "refs/heads/staging"]'), github.ref))
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv with cache and setup python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "0.9.13"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff Formatter
        run: uv run ruff format --check

      - name: Run Ruff Linter
        run: uv run ruff check --exit-zero

      - name: Run ty
        run: uv run ty check

      - name: Run pytest with coverage
        run: uv run pytest --cov=src --cov-report=xml:coverage.xml --cov-report=term-missing

      - name: Minimize uv cache
        run: uv cache prune --ci

  ci-lint-and-tests-all-passed:
      runs-on: ubuntu-latest
      needs: lint-and-test
      if: always()
      steps:
        - name: All checks passed?
          run: |
            if [ "${{ needs.lint-and-test.result }}" != "success" ]; then
              echo "Matrix jobs failed!"
              exit 1
            fi
